import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'common.confirm': 'Confirm',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'hero.badge': 'Real-time Life Saving Network',
    'hero.title.part1': 'Connecting ',
    'hero.title.part2': 'Lives',
    'hero.title.part3': 'One Drop at a Time.',
    'hero.subtitle.home': "An Al-Ribat International initiative — connecting voluntary blood donors with patients in critical need across Bangladesh. Fast, reliable, and secure.",
    'hero.cta.find': 'Find Donor',
    'hero.cta.post': 'Post Emergency',
    'stats.active_donors': 'Active Donors',
    'stats.success_rate': 'Success Rate',
    'stats.lives_saved': 'Lives Saved',
    'stats.hospitals': 'Hospitals',
    'stats.active_requests': 'Active Requests',
    'stats.total_donors': 'Total Donors',
    'home.emergencies.title': 'Active Emergencies',
    'home.emergencies.subtitle': 'Real-time requests needing immediate attention.',
    'home.emergencies.view_all': 'View All',
    'home.emergencies.empty': 'No active emergencies at the moment.',
    'home.cta.title': 'Ready to be a Hero? Register as a Donor.',
    'home.cta.subtitle': 'Your single donation can save up to three lives. Join our network of thousands and make a real impact today.',
    'home.cta.btn': 'Start Saving Lives',
    'home.cta.verified': 'Verified Platform',
    'nav.home': 'Home',
    'nav.emergency': 'Emergency',
    'nav.donors': 'Donors',
    'nav.groups': 'Groups',
    'nav.about': 'About',
    'nav.profile': 'Profile',
    'nav.login': 'Login',
    'nav.notifications': 'Notifications',
    'nav.language': 'Language',
    'nav.english': 'English',
    'nav.bengali': 'Bengali',
    'notifications.empty': 'No new notifications',
    'notifications.mark_all_read': 'Mark all as read',
    'notifications.clear_all': 'Clear all',
    'emergency.title': 'Emergency Requests',
    'emergency.subtitle': 'If you or your family needs blood urgently, post a request here. Our network of donors will be notified immediately.',
    'emergency.post_btn': 'Post Emergency Request',
    'emergency.post_new': 'Post New Request',
    'emergency.live_feed': 'Live Emergency Feed',
    'emergency.fulfilled': 'Fulfilled Cases',
    'emergency.no_requests.title': 'No active requests',
    'emergency.no_requests.subtitle': 'Everything seems to be under control at the moment.',
    'emergency.modal.title': 'Post Emergency',
    'emergency.modal.subtitle': 'Fill in critical details',
    'emergency.modal.blood_type': 'Blood Type',
    'emergency.modal.date': 'Needed Date',
    'emergency.modal.reason': 'Reason for Blood',
    'emergency.modal.reason_placeholder': 'e.g. Surgery, Accident, Thalassemia',
    'emergency.modal.patient_name': 'Patient Name',
    'emergency.modal.patient_placeholder': 'Full name',
    'emergency.modal.urgency': 'Urgency',
    'emergency.modal.urgency_urgent': 'Urgent',
    'emergency.modal.urgency_critical': 'Critical',
    'emergency.modal.urgency_24h': 'Within 24 Hours',
    'emergency.modal.hospital': 'Hospital Name',
    'emergency.modal.hospital_placeholder': 'e.g. Dhaka Medical College Hospital',
    'emergency.modal.bags_needed': 'Bags Needed',
    'emergency.modal.district': 'District',
    'emergency.modal.thana': 'Thana',
    'emergency.modal.contact': 'Contact Number',
    'emergency.modal.contact_placeholder': '+880 1XXX-XXXXXX',
    'emergency.modal.submit': 'Broadcast Emergency',
    'emergency.modal.submitting': 'Posting...',
    'emergency.modal.success.title': 'Request Posted!',
    'emergency.modal.success.subtitle': 'Our donors have been notified immediately.',
    'emergency.active_requests': 'Active Requests',
    'emergency.card.near_you': 'Near You',
    'emergency.card.help_now': 'Help Now',
    'emergency.card.fulfilled': 'Fulfilled',
    'emergency.card.needed': 'Needed',
    'emergency.card.bags': 'Bags',
    'emergency.card.asap': 'ASAP',
    'emergency.card.type': 'Type',
    'emergency.card.medical_emergency': 'Medical Emergency',
    'emergency.cases_handled': 'Cases Handled',
    'emergency.search_placeholder': 'Search by hospital, patient or reason...',
    'donors.title': 'Donors',
    'donors.subtitle': 'Search across registered donors in Bangladesh.',
    'donors.search_placeholder': 'Search by name, blood type, or location...',
    'donors.search_area': 'Search area or name...',
    'donors.filter.btn': 'Filters',
    'donors.filter.all_blood': 'All Blood Types',
    'donors.filter.all_districts': 'All Districts',
    'donors.filter.all_thanas': 'All Thanas',
    'donors.filter.blood_type': 'Blood Type',
    'donors.filter.district': 'District',
    'donors.filter.thana': 'Thana',
    'donors.filter.any_status': 'Any Availability',
    'donors.filter.emergency_only': 'Emergency Only',
    'donors.filter.organ_only': 'Organ Donors Only',
    'donors.filter.clear': 'Clear',
    'donors.filter.clear_all': 'Clear All Filters',
    'donors.view.list': 'List',
    'donors.view.map': 'Map',
    'donors.no_results.title': 'No donors found',
    'donors.no_results.subtitle': "We couldn't find any donors matching your current filters. Try broadening your search.",
    'donors.list.verified': 'Verified',
    'donors.list.never': 'Never',
    'donors.list.donations': 'Donations',
    'donors.list.view_profile': 'View Profile',
    'donors.list.call_now': 'Call Now',
    'donors.list.blood_type': 'Blood Type',
    'donors.list.available': 'Available',
    'donors.list.not_available': 'Not Available',
    'donors.list.emergency_only': 'Emergency Only',
    'donors.map.location': 'Location',
    'donors.map.available_donors': 'Available Donors',
    'donors.map.in_this_location': 'In this location',
    'donors.map.blood_type_summary': 'Blood Type Summary',
    'register.title': 'Become a Donor',
    'register.subtitle': 'Join our mission to ensure blood availability for everyone.',
    'register.step1.title': 'Personal Information',
    'register.step2.title': 'Contact & Location',
    'register.step3.title': 'Medical Information',
    'register.full_name': 'Full Name',
    'register.full_name_placeholder': 'Enter your full name',
    'register.blood_type': 'Blood Type',
    'register.blood_type_placeholder': 'Select Blood Type',
    'register.dob': 'Date of Birth',
    'register.gender': 'Gender',
    'register.gender.male': 'Male',
    'register.gender.female': 'Female',
    'register.gender.other': 'Other',
    'register.district': 'District',
    'register.district_placeholder': 'Select District',
    'register.thana': 'Thana / Area',
    'register.thana_placeholder': 'Select Thana',
    'register.thana_placeholder_district': 'Select District First',
    'register.phone': 'Phone Number',
    'register.phone_placeholder': '+880 1XXX-XXXXXX',
    'register.email': 'Email Address',
    'register.email_placeholder': 'your@email.com',
    'register.weight': 'Weight (kg)',
    'register.weight_placeholder': 'e.g. 70',
    'register.last_donation': 'Last Donation Date',
    'register.total_donations': 'Total Donations',
    'register.total_donations_placeholder': 'e.g. 5',
    'register.medical_conditions': 'Medical Conditions (Optional)',
    'register.medical_conditions_placeholder': 'List any chronic diseases or medications',
    'register.organ_donor_interest': 'I am also interested in being an Organ Donor',
    'register.next': 'Next Step',
    'register.back': 'Back',
    'register.complete': 'Complete Registration',
    'register.processing': 'Processing...',
    'register.success.title': 'Registration Successful!',
    'register.success.subtitle': 'Thank you for joining ARI Blood Net. Your contribution will help save lives across Bangladesh.',
    'register.go_home': 'Go to Home',
    'profile.title': 'My Profile',
    'profile.subtitle': 'Manage account & donor status',
    'profile.completion': 'Profile Completion',
    'profile.sign_out': 'Sign Out',
    'profile.basic_info': 'Basic Information',
    'profile.full_name': 'Full Name',
    'profile.email': 'Email Address',
    'profile.phone': 'Phone Number',
    'profile.district': 'District',
    'profile.thana': 'Thana',
    'profile.donor_status': 'Donor Status',
    'profile.donor_status_active': 'You are listed as a blood donor',
    'profile.donor_status_inactive': 'Become a donor and help save lives',
    'profile.blood_type': 'Blood Type',
    'profile.availability': 'Availability',
    'profile.availability.available': 'Available',
    'profile.availability.not_available': 'Not Available',
    'profile.availability.emergency_only': 'Emergency Only',
    'profile.gender': 'Gender',
    'profile.dob': 'Date of Birth',
    'profile.age_suffix': 'Yrs Old',
    'profile.weight': 'Weight (kg)',
    'profile.height': 'Height (cm)',
    'profile.bmi_score': 'BMI Score',
    'profile.bmi.underweight': 'Underweight',
    'profile.bmi.normal': 'Normal',
    'profile.bmi.overweight': 'Overweight',
    'profile.bmi.obese': 'Obese',
    'profile.bmi.msg_underweight': 'Consider a healthy weight gain plan to maintain your energy for donations.',
    'profile.bmi.msg_normal': 'Great! Your BMI is within the healthy range. Keep up the good work!',
    'profile.bmi.msg_other': 'Maintaining a healthy weight improves your overall donation experience and recovery.',
    'profile.last_donation': 'Last Donation Date',
    'profile.total_donations': 'Total Donations',
    'profile.organ_donor_interest': 'I am also interested in being an Organ Donor',
    'profile.save': 'Save Profile',
    'profile.saving': 'Saving...',
    'profile.success': 'Profile updated successfully!',
    'auth.welcome_back': 'Welcome Back',
    'auth.create_account': 'Create Account',
    'auth.signin_subtitle': 'Sign in to manage your profile',
    'auth.signup_subtitle': 'Join our community of life savers',
    'auth.check_email': 'Check your email',
    'auth.confirmation_sent': "We've sent a confirmation link to",
    'auth.complete_registration': 'Please verify your email to complete registration.',
    'auth.back_to_login': 'Back to Login',
    'auth.full_name': 'Full Name',
    'auth.full_name_placeholder': 'Enter your full name',
    'auth.email': 'Email Address',
    'auth.email_placeholder': 'your@email.com',
    'auth.password': 'Password',
    'auth.password_placeholder': '••••••••',
    'auth.signin_button': 'Sign In',
    'auth.signup_button': 'Create Account',
    'auth.processing': 'Processing...',
    'auth.no_account': "Don't have an account?",
    'auth.have_account': 'Already have an account?',
    'auth.signup_link': 'Sign Up',
    'auth.signin_link': 'Sign In',
    'auth.secure_auth': 'Secure Auth by Supabase',
    'common.loading': 'Loading...',
    'common.no_results': 'No results found',
    'common.back': 'Back',
    'common.submit': 'Submit',
    'common.location': 'Location',
    'common.available': 'Available',
    'common.unavailable': 'Unavailable',
    'common.select': 'Select',
    'common.select_district': 'Select District',
    'common.select_thana': 'Select Thana',
    'donors.filter.location': 'Location',

    // About Page
    'about.badge': 'About Us',
    'about.hero.title': 'Connecting Hearts, Saving Lives',
    'about.hero.subtitle': 'We are a community-driven platform dedicated to bridging the gap between blood donors and those in urgent need across Bangladesh.',
    'about.mission.title': 'Our Mission',
    'about.mission.text': 'To create a seamless, technology-driven ecosystem where no life is lost due to the unavailability of blood. We empower individuals to become heroes in their communities.',
    'about.why.title': 'Why Donate Blood?',
    'about.why.save_lives.title': 'Save Lives',
    'about.why.save_lives.text': 'A single donation can save up to three lives. Your blood is a lifeline for someone in critical condition.',
    'about.why.health.title': 'Health Benefits',
    'about.why.health.text': 'Regular donation helps in maintaining healthy iron levels and reduces the risk of cardiovascular diseases.',
    'about.why.community.title': 'Community Impact',
    'about.why.community.text': 'Be part of a noble cause that strengthens the social fabric and saves fellow citizens in times of crisis.',
    'about.faq.title': 'Common Questions',
    'about.faq.q1': 'Who can donate blood?',
    'about.faq.a1': 'Anyone between 18-65 years old, weighing at least 50kg, and in good general health can usually donate.',
    'about.faq.q2': 'How often can I donate?',
    'about.faq.a2': 'You can safely donate whole blood every 3 to 4 months (90-120 days) to allow your body to replenish.',
    'about.faq.q3': 'Is it safe to donate?',
    'about.faq.a3': 'Yes, it\'s completely safe. We use sterile, single-use equipment for every donor to ensure zero risk of infection.',
    'about.dev.title': 'About Al-Ribat International',
    'about.dev.company': 'Al-Ribat International',
    'about.dev.description': 'Al-Ribat International is a young and ambitious company based in Dhaka, Bangladesh, specializing in import and shipping services from China to Bangladesh. We serve everyone from individual buyers to small businesses and large enterprises with reliability, transparency, and care.\n\nBut for us, business is never just about profit.\n\nFrom the very beginning, we believed that a company has a responsibility toward its people and its nation. That belief gave birth to Al-Ribat Care, a free blood donation platform connecting voluntary donors with patients in critical need across Bangladesh.\n\nWe have just begun our journey. Our vision is to expand nationwide and grow Al-Ribat Care into a complete humanitarian platform covering blood donation, emergency aid, and essential health services for all.\n\nWe build businesses. We build communities. We save lives.\n— Al-Ribat International',
    'about.dev.facebook': 'Facebook',
    'about.cta.title': 'Ready to make a difference?',
    'about.cta.subtitle': 'Join our growing community of life-savers today. Your one decision could be someone\'s second chance at life.',
    'about.cta.register': 'Register as Donor',
    'about.cta.support': 'Contact Support',

    // Donor Profile Page
    'donor.profile.loading': 'Loading donor profile...',
    'donor.profile.not_found': 'Donor Not Found',
    'donor.profile.go_back': 'Go Back',
    'donor.profile.verified': 'Verified',
    'donor.profile.last_donated_label': 'Last:',
    'donor.profile.update_availability': 'Update Availability',
    'donor.profile.edit_profile': 'Edit Full Profile',
    'donor.profile.member_since': 'Member since',
    'donor.profile.total_donations': 'Total Donations',
    'donor.profile.first_time': 'First Time',
    'donor.profile.age': 'Donor Age',
    'donor.profile.years': 'Years',
    'donor.profile.health_bmi': 'Health & BMI',
    'donor.profile.bmi': 'BMI',
    'donor.profile.healthy': 'Healthy',
    'donor.profile.last_donated': 'Last Donated',
    'donor.profile.ready': 'Ready',
    'donor.profile.title': 'Donor Profile',
    'donor.profile.about_text1': 'is a dedicated voluntary blood donor from',
    'donor.profile.about_text2': '.',
    'donor.profile.organ_donor_text': ' They are also a registered organ donor, committed to saving lives in every way possible.',
    'donor.profile.impact_text1': 'By maintaining a healthy lifestyle and regular donations, ',
    'donor.profile.impact_text2': ' has contributed to the safety and well-being of the community.',
    'donor.profile.blood_group': 'Blood Group',
    'donor.profile.gender': 'Gender',
    'donor.profile.organ_donor': 'Organ Donor',
    'donor.profile.impact_title': 'Donation Impact',
    'donor.profile.lives_saved': 'Lives potentially saved through blood donations',
    'donor.profile.impact_desc': 'Each blood donation can save up to three lives. ',
    'donor.profile.impact_desc2': '\'s commitment to voluntary donation is a testament to their humanitarian spirit.',
    'donor.profile.hero_donor': 'Hero Donor',
    'donor.profile.readiness_title': 'Donation Readiness',
    'donor.profile.ready_to_donate': 'Ready to Donate',
    'donor.profile.recovery_period': 'Recovery Period',
    'donor.profile.ready_desc': 'This donor has no recent donations recorded and is eligible to donate immediately.',
    'donor.profile.eligible_desc': 'It has been more than 3 months since the last donation. The donor is physically ready for their next contribution.',
    'donor.profile.recovery_desc': 'The donor is currently in a recovery period. They will be eligible to donate again after ',
    'donor.profile.medical_title': 'Medical Information',
    'donor.profile.weight': 'Weight',
    'donor.profile.height': 'Height',
    'donor.profile.medical_conditions': 'Medical Conditions',
    'donor.profile.quick_actions': 'Quick Actions',
    'donor.profile.call_now': 'Call Now',
    'donor.profile.send_email': 'Send Email',
    'donor.profile.privacy_notice': 'Please respect the donor\'s privacy and only contact for genuine blood requests.',
    'donor.profile.safety_title': 'Safety First',
    'donor.profile.safety_rule1': 'Verify the hospital requirements first',
    'donor.profile.safety_rule2': 'Bring a valid ID for the donation',
    'donor.profile.safety_rule3': 'Ensure the donor is well-rested',
    'donor.profile.safety_rule4': 'Provide transportation if possible',
    
    // Groups Page
    'groups.title': 'Organizations & Groups',
    'groups.subtitle': 'Connect with local blood donation clubs, NGOs, and volunteer groups across Bangladesh.',
    'groups.create_btn': 'Register Group',
    'groups.search_placeholder': 'Search groups by name or location...',
    'groups.filter.all_districts': 'All Districts',
    'groups.filter.all_thanas': 'All Thanas',
    'groups.no_results.title': 'No groups found',
    'groups.no_results.subtitle': 'Try adjusting your search or location filters.',
    'groups.card.members': 'Members',
    'groups.card.view_details': 'View Details',
    'groups.card.view_group': 'View Group',
    'groups.modal.title': 'Register New Group',
    'groups.modal.subtitle': 'Create a community for your organization',
    'groups.modal.name': 'Group Name',
    'groups.modal.name_placeholder': 'e.g. Sandhani, Badhan, Local Youth Club',
    'groups.modal.description': 'Description',
    'groups.modal.description_placeholder': 'Tell us about your group\'s mission...',
    'groups.modal.district': 'District',
    'groups.modal.thana': 'Thana',
    'groups.modal.logo_url': 'Logo URL (Optional)',
    'groups.modal.facebook': 'Facebook Page URL (Optional)',
    'groups.modal.website': 'Website URL (Optional)',
    'groups.modal.submit': 'Create Group',
    'groups.modal.update_btn': 'Update Group',
    'groups.modal.edit_title': 'Edit Group Details',
    'groups.modal.success.title': 'Group Registered!',
    'groups.modal.success.subtitle': 'Your organization is now live on ARI Blood Net.',
    'groups.details.about': 'About',
    'groups.details.location': 'Based in',
    'groups.details.members_title': 'Group Members',
    'groups.details.join_btn': 'Join Group',
    'groups.details.leave_btn': 'Leave Group',
    'groups.details.edit_btn': 'Edit Group',
    'groups.details.delete_btn': 'Delete Group',
    'groups.details.delete_confirm': 'Are you sure you want to delete this group? This action cannot be undone.',
    'groups.details.social_links': 'Social Links',
    'groups.details.admin_badge': 'Admin',
    'groups.details.no_members': 'No members in this group yet.',
    'groups.details.add_member': 'Add Member',
    'groups.details.search_donors': 'Search donors to add...',
    'groups.details.add_success': 'Member added successfully!',
    'groups.details.already_member': 'Already a member',
  },
  bn: {
    'common.confirm': 'নিশ্চিত করুন',
    'common.cancel': 'বাতিল করুন',
    'common.delete': 'ডিলিট করুন',
    'common.add': 'যোগ করুন',
    'hero.badge': 'রিয়েল-টাইম জীবন রক্ষাকারী নেটওয়ার্ক',
    'hero.title.part1': 'জীবন ',
    'hero.title.part2': 'যুক্ত করছি',
    'hero.title.part3': 'এক ফোঁটা রক্তে।',
    'hero.subtitle.home': 'আল-রিবাত ইন্টারন্যাশনালের একটি উদ্যোগ — সারা বাংলাদেশে স্বেচ্ছায় রক্তদাতাদের জরুরি রোগীদের সাথে যুক্ত করা। দ্রুত, নির্ভরযোগ্য এবং নিরাপদ।',
    'hero.cta.find': 'দাতা খুঁজুন',
    'hero.cta.post': 'জরুরি পোস্ট',
    'stats.active_donors': 'সক্রিয় দাতা',
    'stats.success_rate': 'সাফল্যের হার',
    'stats.lives_saved': 'জীবন রক্ষা',
    'stats.hospitals': 'হাসপাতাল',
    'stats.active_requests': 'সক্রিয় অনুরোধ',
    'stats.total_donors': 'মোট দাতা',
    'home.emergencies.title': 'সক্রিয় জরুরি অবস্থা',
    'home.emergencies.subtitle': 'তাত্ক্ষণিক মনোযোগ প্রয়োজন এমন রিয়েল-টাইম অনুরোধ।',
    'home.emergencies.view_all': 'সব দেখুন',
    'home.emergencies.empty': 'এই মুহূর্তে কোন সক্রিয় জরুরি অবস্থা নেই।',
    'home.cta.title': 'হিরো হতে প্রস্তুত? দাতা হিসেবে নিবন্ধন করুন।',
    'home.cta.subtitle': 'আপনার একটি রক্তদান তিনটি জীবন বাঁচাতে পারে। আমাদের হাজার হাজার নেটওয়ার্কে যোগ দিন এবং আজই প্রকৃত প্রভাব ফেলুন।',
    'home.cta.verified': 'ভেরিফাইড প্ল্যাটফর্ম',
    'home.cta.btn': 'জীবন বাঁচানো শুরু করুন',
    'nav.home': 'হোম',
    'nav.emergency': 'জরুরি',
    'nav.donors': 'দাতা',
    'nav.groups': 'গ্রুপ',
    'nav.about': 'সম্পর্কে',
    'nav.profile': 'প্রোফাইল',
    'nav.login': 'লগইন',
    'nav.notifications': 'নোটিফিকেশন',
    'nav.language': 'ভাষা',
    'nav.english': 'ইংরেজি',
    'nav.bengali': 'বাংলা',
    'notifications.empty': 'কোনো নতুন নোটিফিকেশন নেই',
    'notifications.mark_all_read': 'সব পড়া হয়েছে হিসেবে চিহ্নিত করুন',
    'notifications.clear_all': 'সব মুছুন',
    'emergency.title': 'জরুরি অনুরোধ',
    'emergency.subtitle': 'আপনার বা আপনার পরিবারের জরুরিভাবে রক্তের প্রয়োজন হলে এখানে একটি অনুরোধ পোস্ট করুন। আমাদের দাতাদের নেটওয়ার্ক অবিলম্বে অবহিত করা হবে।',
    'emergency.post_new': 'নতুন অনুরোধ পোস্ট করুন',
    'emergency.live_feed': 'লাইভ ইমার্জেন্সি ফিড',
    'emergency.fulfilled': 'সম্পন্ন কেস',
    'emergency.no_requests.title': 'কোনো সক্রিয় অনুরোধ নেই',
    'emergency.no_requests.subtitle': 'এই মুহূর্তে সবকিছু নিয়ন্ত্রণে আছে বলে মনে হচ্ছে।',
    'emergency.modal.title': 'জরুরি অনুরোধ পোস্ট করুন',
    'emergency.modal.subtitle': 'গুরুত্বপূর্ণ তথ্য পূরণ করুন',
    'emergency.modal.blood_type': 'রক্তের গ্রুপ',
    'emergency.modal.date': 'প্রয়োজনের তারিখ',
    'emergency.modal.reason': 'রক্তের কারণ',
    'emergency.modal.reason_placeholder': 'যেমন: সার্জারি, দুর্ঘটনা, থ্যালাসেমিয়া',
    'emergency.modal.patient_name': 'রোগীর নাম',
    'emergency.modal.patient_placeholder': 'পুরো নাম',
    'emergency.modal.urgency': 'জরুরিতা',
    'emergency.modal.urgency_urgent': 'জরুরি',
    'emergency.modal.urgency_critical': 'সংকটাপন্ন',
    'emergency.modal.urgency_24h': '২৪ ঘণ্টার মধ্যে',
    'emergency.modal.hospital': 'হাসপাতালের নাম',
    'emergency.modal.hospital_placeholder': 'যেমন: ঢাকা মেডিকেল কলেজ হাসপাতাল',
    'emergency.modal.bags_needed': 'রক্তের ব্যাগের সংখ্যা',
    'emergency.modal.district': 'জেলা',
    'emergency.modal.thana': 'থানা',
    'emergency.modal.contact': 'যোগাযোগের নম্বর',
    'emergency.modal.contact_placeholder': '+৮৮০ ১XXX-XXXXXX',
    'emergency.modal.submit': 'জরুরি অনুরোধ প্রচার করুন',
    'emergency.modal.submitting': 'পোস্ট করা হচ্ছে...',
    'emergency.modal.success.title': 'অনুরোধ পোস্ট করা হয়েছে!',
    'emergency.modal.success.subtitle': 'আমাদের দাতাদের অবিলম্বে অবহিত করা হয়েছে।',
    'emergency.active_requests': 'সক্রিয় অনুরোধ',
    'emergency.card.near_you': 'আপনার কাছে',
    'emergency.card.help_now': 'এখনই সাহায্য করুন',
    'emergency.card.fulfilled': 'সম্পন্ন',
    'emergency.card.needed': 'প্রয়োজন',
    'emergency.card.bags': 'ব্যাগ',
    'emergency.card.asap': 'যত দ্রুত সম্ভব',
    'emergency.card.type': 'ধরণ',
    'emergency.card.medical_emergency': 'চিকিৎসা জরুরি অবস্থা',
    'emergency.cases_handled': 'কেস হ্যান্ডেল করা হয়েছে',
    'emergency.search_placeholder': 'হাসপাতাল, রোগী বা কারণ দিয়ে খুঁজুন...',
    'donors.title': 'দাতা',
    'donors.subtitle': 'বাংলাদেশে নিবন্ধিত দাতাদের মধ্যে খুঁজুন।',
    'donors.search_placeholder': 'নাম, রক্তের গ্রুপ বা অবস্থান দিয়ে খুঁজুন...',
    'donors.search_area': 'এলাকা বা নাম দিয়ে খুঁজুন...',
    'donors.filter.btn': 'ফিল্টার',
    'donors.filter.all_blood': 'সব রক্তের গ্রুপ',
    'donors.filter.all_districts': 'সব জেলা',
    'donors.filter.all_thanas': 'সব থানা',
    'donors.filter.blood_type': 'রক্তের গ্রুপ',
    'donors.filter.district': 'জেলা',
    'donors.filter.thana': 'থানা',
    'donors.filter.any_status': 'যেকোনো প্রাপ্যতা',
    'donors.filter.emergency_only': 'শুধুমাত্র জরুরি',
    'donors.filter.organ_only': 'শুধুমাত্র অঙ্গ দাতা',
    'donors.filter.clear': 'মুছুন',
    'donors.filter.clear_all': 'সব ফিল্টার মুছুন',
    'donors.view.list': 'তালিকা',
    'donors.view.map': 'মানচিত্র',
    'donors.no_results.title': 'কোন দাতা পাওয়া যায়নি',
    'donors.no_results.subtitle': 'আপনার বর্তমান ফিল্টারের সাথে মিলছে এমন কোন দাতা আমরা খুঁজে পাইনি। আপনার অনুসন্ধান আরও বিস্তৃত করার চেষ্টা করুন।',
    'donors.list.verified': 'ভেরিফাইড',
    'donors.list.never': 'কখনো না',
    'donors.list.donations': 'রক্তদান',
    'donors.list.view_profile': 'প্রোফাইল দেখুন',
    'donors.list.call_now': 'কল করুন',
    'donors.list.blood_type': 'রক্তের গ্রুপ',
    'donors.list.available': 'উপলব্ধ',
    'donors.list.not_available': 'উপলব্ধ নেই',
    'donors.list.emergency_only': 'শুধুমাত্র জরুরি',
    'donors.map.location': 'অবস্থান',
    'donors.map.available_donors': 'উপলব্ধ দাতা',
    'donors.map.in_this_location': 'এই অবস্থানে',
    'donors.map.blood_type_summary': 'রক্তের গ্রুপের সারসংক্ষেপ',
    'register.title': 'দাতা হন',
    'register.subtitle': 'সবার জন্য রক্তের প্রাপ্যতা নিশ্চিত করতে আমাদের মিশনে যোগ দিন।',
    'register.step1.title': 'ব্যক্তিগত তথ্য',
    'register.step2.title': 'যোগাযোগ ও অবস্থান',
    'register.step3.title': 'চিকিৎসা সংক্রান্ত তথ্য',
    'register.full_name': 'পুরো নাম',
    'register.full_name_placeholder': 'আপনার পুরো নাম লিখুন',
    'register.blood_type': 'রক্তের গ্রুপ',
    'register.blood_type_placeholder': 'রক্তের গ্রুপ নির্বাচন করুন',
    'register.dob': 'জন্ম তারিখ',
    'register.gender': 'লিঙ্গ',
    'register.gender.male': 'পুরুষ',
    'register.gender.female': 'মহিলা',
    'register.gender.other': 'অন্যান্য',
    'register.district': 'জেলা',
    'register.district_placeholder': 'জেলা নির্বাচন করুন',
    'register.thana': 'থানা / এলাকা',
    'register.thana_placeholder': 'থানা নির্বাচন করুন',
    'register.thana_placeholder_district': 'প্রথমে জেলা নির্বাচন করুন',
    'register.phone': 'ফোন নম্বর',
    'register.phone_placeholder': '+৮৮০ ১XXX-XXXXXX',
    'register.email': 'ইমেইল ঠিকানা',
    'register.email_placeholder': 'your@email.com',
    'register.weight': 'ওজন (কেজি)',
    'register.weight_placeholder': 'যেমন: ৭০',
    'register.last_donation': 'শেষ রক্তদানের তারিখ',
    'register.total_donations': 'মোট রক্তদান',
    'register.total_donations_placeholder': 'যেমন: ৫',
    'register.medical_conditions': 'চিকিৎসা সংক্রান্ত অবস্থা (ঐচ্ছিক)',
    'register.medical_conditions_placeholder': 'কোনো দীর্ঘস্থায়ী রোগ বা ওষুধের তালিকা দিন',
    'register.organ_donor_interest': 'আমি অঙ্গ দাতা হতেও আগ্রহী',
    'register.next': 'পরবর্তী ধাপ',
    'register.back': 'পিছনে',
    'register.complete': 'নিবন্ধন সম্পন্ন করুন',
    'register.processing': 'প্রক্রিয়াকরণ হচ্ছে...',
    'register.success.title': 'নিবন্ধন সফল হয়েছে!',
    'register.success.subtitle': 'এআরআই ব্লাড নেট-এ যোগদানের জন্য আপনাকে ধন্যবাদ। আপনার অবদান সারা বাংলাদেশে জীবন বাঁচাতে সাহায্য করবে।',
    'register.go_home': 'হোমে যান',
    'profile.title': 'আমার প্রোফাইল',
    'profile.subtitle': 'অ্যাকাউন্ট ও দাতার স্ট্যাটাস পরিচালনা করুন',
    'profile.completion': 'প্রোফাইল সম্পূর্ণতা',
    'profile.sign_out': 'সাইন আউট',
    'profile.basic_info': 'প্রাথমিক তথ্য',
    'profile.full_name': 'পুরো নাম',
    'profile.email': 'ইমেইল ঠিকানা',
    'profile.phone': 'ফোন নম্বর',
    'profile.district': 'জেলা',
    'profile.thana': 'থানা',
    'profile.donor_status': 'দাতার স্ট্যাটাস',
    'profile.donor_status_active': 'আপনি একজন রক্তদাতা হিসেবে তালিকাভুক্ত',
    'profile.donor_status_inactive': 'দাতা হন এবং জীবন বাঁচাতে সাহায্য করুন',
    'profile.blood_type': 'রক্তের গ্রুপ',
    'profile.availability': 'প্রাপ্যতা',
    'profile.availability.available': 'উপলব্ধ',
    'profile.availability.not_available': 'উপলব্ধ নেই',
    'profile.availability.emergency_only': 'শুধুমাত্র জরুরি অবস্থা',
    'profile.gender': 'লিঙ্গ',
    'profile.dob': 'জন্ম তারিখ',
    'profile.age_suffix': 'বছর বয়স',
    'profile.weight': 'ওজন (কেজি)',
    'profile.height': 'উচ্চতা (সেমি)',
    'profile.bmi_score': 'বিএমআই স্কোর',
    'profile.bmi.underweight': 'কম ওজন',
    'profile.bmi.normal': 'স্বাভাবিক',
    'profile.bmi.overweight': 'অতিরিক্ত ওজন',
    'profile.bmi.obese': 'স্থূল',
    'profile.bmi.msg_underweight': 'রক্তদানের জন্য আপনার শক্তি বজায় রাখতে একটি স্বাস্থ্যকর ওজন বৃদ্ধির পরিকল্পনা বিবেচনা করুন।',
    'profile.bmi.msg_normal': 'চমৎকার! আপনার বিএমআই স্বাভাবিক সীমার মধ্যে আছে। ভালো কাজ চালিয়ে যান!',
    'profile.bmi.msg_other': 'স্বাস্থ্যকর ওজন বজায় রাখা আপনার সামগ্রিক রক্তদানের অভিজ্ঞতা এবং পুনরুদ্ধারে উন্নতি করে।',
    'profile.last_donation': 'শেষ রক্তদানের তারিখ',
    'profile.total_donations': 'মোট রক্তদান',
    'profile.organ_donor_interest': 'আমি অঙ্গ দাতা হতেও আগ্রহী',
    'profile.save': 'প্রোফাইল সংরক্ষণ করুন',
    'profile.saving': 'সংরক্ষণ হচ্ছে...',
    'profile.success': 'প্রোফাইল সফলভাবে আপডেট করা হয়েছে!',
    'auth.welcome_back': 'স্বাগতম',
    'auth.create_account': 'অ্যাকাউন্ট তৈরি করুন',
    'auth.signin_subtitle': 'আপনার প্রোফাইল পরিচালনা করতে সাইন ইন করুন',
    'auth.signup_subtitle': 'আমাদের জীবন রক্ষাকারী সম্প্রদায়ে যোগ দিন',
    'auth.check_email': 'আপনার ইমেইল চেক করুন',
    'auth.confirmation_sent': 'আমরা একটি নিশ্চিতকরণ লিঙ্ক পাঠিয়েছি',
    'auth.complete_registration': 'নিবন্ধন সম্পন্ন করতে আপনার ইমেইল যাচাই করুন।',
    'auth.back_to_login': 'লগইনে ফিরে যান',
    'auth.full_name': 'পুরো নাম',
    'auth.full_name_placeholder': 'আপনার পুরো নাম লিখুন',
    'auth.email': 'ইমেইল ঠিকানা',
    'auth.email_placeholder': 'your@email.com',
    'auth.password': 'পাসওয়ার্ড',
    'auth.password_placeholder': '••••••••',
    'auth.signin_button': 'সাইন ইন',
    'auth.signup_button': 'অ্যাকাউন্ট তৈরি করুন',
    'auth.processing': 'প্রক্রিয়াকরণ হচ্ছে...',
    'auth.no_account': 'অ্যাকাউন্ট নেই?',
    'auth.have_account': 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    'auth.signup_link': 'সাইন আপ',
    'auth.signin_link': 'সাইন ইন',
    'auth.secure_auth': 'সুপাবেস দ্বারা সুরক্ষিত অথ',
    'common.loading': 'লোড হচ্ছে...',
    'common.no_results': 'কোন ফলাফল পাওয়া যায়নি',
    'common.back': 'ফিরে যান',
    'common.submit': 'জমা দিন',
    'common.location': 'অবস্থান',
    'common.available': 'উপলব্ধ',
    'common.unavailable': 'অনুপলব্ধ',
    'common.select': 'নির্বাচন করুন',
    'common.select_district': 'জেলা নির্বাচন করুন',
    'common.select_thana': 'থানা নির্বাচন করুন',
    'donors.filter.location': 'অবস্থান',

    // About Page
    'about.badge': 'আমাদের সম্পর্কে',
    'about.hero.title': 'হৃদয় যুক্ত করছি, জীবন বাঁচাচ্ছি',
    'about.hero.subtitle': 'আমরা একটি সম্প্রদায়-চালিত প্ল্যাটফর্ম যা সারা বাংলাদেশে রক্তদাতা এবং জরুরি প্রয়োজনে থাকা ব্যক্তিদের মধ্যে দূরত্ব কমিয়ে আনতে কাজ করছে।',
    'about.mission.title': 'আমাদের লক্ষ্য',
    'about.mission.text': 'একটি নিরবচ্ছিন্ন, প্রযুক্তি-চালিত ইকোসিস্টেম তৈরি করা যেখানে রক্তের অভাবে কোনো প্রাণ হারাবে না। আমরা ব্যক্তিদের তাদের সম্প্রদায়ের নায়ক হতে ক্ষমতায়ন করি।',
    'about.why.title': 'রক্তদান কেন করবেন?',
    'about.why.save_lives.title': 'জীবন বাঁচান',
    'about.why.save_lives.text': 'একটি একক দান তিনজনের প্রাণ বাঁচাতে পারে। আপনার রক্ত সংকটাপন্ন কারো জন্য জীবনরেখা।',
    'about.why.health.title': 'স্বাস্থ্য সুবিধা',
    'about.why.health.text': 'নিয়মিত দান আয়রনের মাত্রা ঠিক রাখতে সাহায্য করে এবং হৃদরোগের ঝুঁকি কমায়।',
    'about.why.community.title': 'সামাজিক প্রভাব',
    'about.why.community.text': 'একটি মহৎ কাজের অংশ হোন যা সামাজিক বন্ধন দৃঢ় করে এবং সংকটের সময় নাগরিকদের রক্ষা করে।',
    'about.faq.title': 'সাধারণ প্রশ্নাবলী',
    'about.faq.q1': 'কে রক্তদান করতে পারে?',
    'about.faq.a1': '১৮-৬৫ বছর বয়সী, কমপক্ষে ৫০ কেজি ওজন এবং সুস্বাস্থ্যের অধিকারী যে কেউ সাধারণত রক্তদান করতে পারেন।',
    'about.faq.q2': 'আমি কত ঘনঘন রক্তদান করতে পারি?',
    'about.faq.a2': 'আপনি নিরাপদে প্রতি ৩ থেকে ৪ মাস (৯০-১২০ দিন) অন্তর রক্তদান করতে পারেন যাতে আপনার শরীর রক্ত পূরণ করতে পারে।',
    'about.faq.q3': 'রক্তদান কি নিরাপদ?',
    'about.faq.a3': 'হ্যাঁ, এটি সম্পূর্ণ নিরাপদ। সংক্রমণের ঝুঁকি শূন্য করতে আমরা প্রতিটি দাতার জন্য জীবাণুমুক্ত, একবার ব্যবহারযোগ্য সরঞ্জাম ব্যবহার করি।',
    'about.dev.title': 'আল-রিবাত ইন্টারন্যাশনাল সম্পর্কে',
    'about.dev.company': 'আল-রিবাত ইন্টারন্যাশনাল',
    'about.dev.description': 'আল-রিবাত ইন্টারন্যাশনাল একটি নতুন কিন্তু স্বপ্নবাজ প্রতিষ্ঠান। আমরা চায়না থেকে বাংলাদেশে পণ্য আমদানি ও শিপিং সেবা প্রদান করি ছোট উদ্যোক্তা থেকে শুরু করে বড় ব্যবসায়ী, সবার জন্য।\n\nকিন্তু আমরা শুধু ব্যবসায় বিশ্বাস করি না। আমরা বিশ্বাস করি মানুষের সেবায়।\n\nএই বিশ্বাস থেকেই জন্ম নিয়েছে আল-রিবাত কেয়ার, আমাদের রক্তদান অ্যাপ। যেখানে একজন দাতার রক্ত পৌঁছে যাবে একজন সংকটাপন্ন মানুষের কাছে দ্রুত, নির্ভরযোগ্যভাবে।\n\nআমাদের যাত্রা সবে শুরু হয়েছে। আমাদের স্বপ্ন সারা বাংলাদেশে ছড়িয়ে পড়া। রক্তদান থেকে শুরু করে জরুরি স্বাস্থ্যসেবা পর্যন্ত আল-রিবাত কেয়ার থাকবে আপনার পাশে।\n\nআমরা ব্যবসা গড়ে তুলি। আমরা সম্প্রদায় গড়ে তুলি। আমরা জীবন বাঁচাই।\n— আল-রিবাত ইন্টারন্যাশনাল।',
    'about.dev.facebook': 'ফেসবুক',
    'about.cta.title': 'পরিবর্তন আনতে প্রস্তুত?',
    'about.cta.subtitle': 'আজই আমাদের ক্রমবর্ধমান জীবন রক্ষাকারী সম্প্রদায়ে যোগ দিন। আপনার একটি সিদ্ধান্ত কারো জীবনের দ্বিতীয় সুযোগ হতে পারে।',
    'about.cta.register': 'দাতা হিসেবে নিবন্ধন করুন',
    'about.cta.support': 'সাপোর্টের সাথে যোগাযোগ করুন',

    // Donor Profile Page
    'donor.profile.loading': 'দাতার প্রোফাইল লোড হচ্ছে...',
    'donor.profile.not_found': 'দাতা খুঁজে পাওয়া যায়নি',
    'donor.profile.go_back': 'ফিরে যান',
    'donor.profile.verified': 'ভেরিফাইড',
    'donor.profile.last_donated_label': 'সর্বশেষ:',
    'donor.profile.update_availability': 'উপলব্ধতা আপডেট করুন',
    'donor.profile.edit_profile': 'সম্পূর্ণ প্রোফাইল এডিট করুন',
    'donor.profile.member_since': 'সদস্য হয়েছেন',
    'donor.profile.total_donations': 'মোট দান',
    'donor.profile.first_time': 'প্রথমবার',
    'donor.profile.age': 'দাতার বয়স',
    'donor.profile.years': 'বছর',
    'donor.profile.health_bmi': 'স্বাস্থ্য ও BMI',
    'donor.profile.bmi': 'BMI',
    'donor.profile.healthy': 'সুস্থ',
    'donor.profile.last_donated': 'সর্বশেষ দান',
    'donor.profile.ready': 'প্রস্তুত',
    'donor.profile.title': 'দাতার প্রোফাইল',
    'donor.profile.about_text1': 'একজন নিবেদিত স্বেচ্ছাসেবী রক্তদাতা',
    'donor.profile.about_text2': 'থেকে।',
    'donor.profile.organ_donor_text': ' তারা একজন নিবন্ধিত অঙ্গদাতাও, সম্ভাব্য সব উপায়ে জীবন বাঁচাতে প্রতিশ্রুতিবদ্ধ।',
    'donor.profile.impact_text1': 'সুস্থ জীবনধারা এবং নিয়মিত রক্তদানের মাধ্যমে, ',
    'donor.profile.impact_text2': ' সমাজের নিরাপত্তা ও কল্যাণে অবদান রেখেছেন।',
    'donor.profile.blood_group': 'রক্তের গ্রুপ',
    'donor.profile.gender': 'লিঙ্গ',
    'donor.profile.organ_donor': 'অঙ্গদাতা',
    'donor.profile.impact_title': 'রক্তদানের প্রভাব',
    'donor.profile.lives_saved': 'রক্তদানের মাধ্যমে সম্ভাব্য জীবন রক্ষা করা হয়েছে',
    'donor.profile.impact_desc': 'প্রতিটি রক্তদান তিনজনের প্রাণ বাঁচাতে পারে। স্বেচ্ছায় রক্তদানের প্রতি ',
    'donor.profile.impact_desc2': '-এর প্রতিশ্রুতি তার মানবিক চেতনার পরিচয় দেয়।',
    'donor.profile.hero_donor': 'হিরো ডোনার',
    'donor.profile.readiness_title': 'রক্তদানের প্রস্তুতি',
    'donor.profile.ready_to_donate': 'রক্তদানের জন্য প্রস্তুত',
    'donor.profile.recovery_period': 'রিকভারি পিরিয়ড',
    'donor.profile.ready_desc': 'এই দাতার কোনো সাম্প্রতিক রক্তদানের রেকর্ড নেই এবং তিনি অবিলম্বে রক্তদানের যোগ্য।',
    'donor.profile.eligible_desc': 'সর্বশেষ রক্তদানের পর ৩ মাসের বেশি সময় পার হয়েছে। দাতা শারীরিকভাবে পরবর্তী রক্তদানের জন্য প্রস্তুত।',
    'donor.profile.recovery_desc': 'দাতা বর্তমানে রিকভারি পিরিয়ডে আছেন। তিনি আবার রক্তদান করতে পারবেন ',
    'donor.profile.medical_title': 'চিকিৎসা সংক্রান্ত তথ্য',
    'donor.profile.weight': 'ওজন',
    'donor.profile.height': 'উচ্চতা',
    'donor.profile.medical_conditions': 'শারীরিক অবস্থা',
    'donor.profile.quick_actions': 'দ্রুত পদক্ষেপ',
    'donor.profile.call_now': 'এখনই কল করুন',
    'donor.profile.send_email': 'ইমেইল পাঠান',
    'donor.profile.privacy_notice': 'দাতার গোপনীয়তাকে সম্মান করুন এবং শুধুমাত্র প্রকৃত রক্তের প্রয়োজনে যোগাযোগ করুন।',
    'donor.profile.safety_title': 'নিরাপত্তা সবার আগে',
    'donor.profile.safety_rule1': 'প্রথমে হাসপাতালের প্রয়োজনীয়তা যাচাই করুন',
    'donor.profile.safety_rule2': 'রক্তদানের জন্য একটি বৈধ আইডি সাথে আনুন',
    'donor.profile.safety_rule3': 'দাতা যেন পর্যাপ্ত বিশ্রাম পায় তা নিশ্চিত করুন',
    'donor.profile.safety_rule4': 'সম্ভব হলে যাতায়াতের ব্যবস্থা করুন',
    
    // Groups Page
    'groups.title': 'সংস্থা ও গ্রুপ',
    'groups.subtitle': 'সারা বাংলাদেশের স্থানীয় রক্তদান ক্লাব, এনজিও এবং স্বেচ্ছাসেবী গ্রুপগুলোর সাথে যুক্ত হোন।',
    'groups.create_btn': 'গ্রুপ নিবন্ধন করুন',
    'groups.search_placeholder': 'নাম বা অবস্থান দিয়ে গ্রুপ খুঁজুন...',
    'groups.filter.all_districts': 'সব জেলা',
    'groups.filter.all_thanas': 'সব থানা',
    'groups.no_results.title': 'কোন গ্রুপ পাওয়া যায়নি',
    'groups.no_results.subtitle': 'আপনার অনুসন্ধান বা অবস্থান ফিল্টার পরিবর্তন করে দেখুন।',
    'groups.card.members': 'সদস্য',
    'groups.card.view_details': 'বিস্তারিত দেখুন',
    'groups.card.view_group': 'গ্রুপ দেখুন',
    'groups.modal.title': 'নতুন গ্রুপ নিবন্ধন করুন',
    'groups.modal.subtitle': 'আপনার সংস্থার জন্য একটি সম্প্রদায় তৈরি করুন',
    'groups.modal.name': 'গ্রুপের নাম',
    'groups.modal.name_placeholder': 'যেমন: সন্ধানী, বাঁধন, স্থানীয় যুব ক্লাব',
    'groups.modal.description': 'বর্ণনা',
    'groups.modal.description_placeholder': 'আপনার গ্রুপের লক্ষ্য সম্পর্কে বলুন...',
    'groups.modal.district': 'জেলা',
    'groups.modal.thana': 'থানা',
    'groups.modal.logo_url': 'লোগো ইউআরএল (ঐচ্ছিক)',
    'groups.modal.facebook': 'ফেসবুক পেজ ইউআরএল (ঐচ্ছিক)',
    'groups.modal.website': 'ওয়েবসাইট ইউআরএল (ঐচ্ছিক)',
    'groups.modal.submit': 'গ্রুপ তৈরি করুন',
    'groups.modal.update_btn': 'গ্রুপ আপডেট করুন',
    'groups.modal.edit_title': 'গ্রুপের তথ্য এডিট করুন',
    'groups.modal.success.title': 'গ্রুপ নিবন্ধিত হয়েছে!',
    'groups.modal.success.subtitle': 'আপনার সংস্থা এখন এআরআই ব্লাড নেট-এ লাইভ।',
    'groups.details.about': 'সম্পর্কে',
    'groups.details.location': 'অবস্থান',
    'groups.details.members_title': 'গ্রুপ সদস্য',
    'groups.details.join_btn': 'গ্রুপে যোগ দিন',
    'groups.details.leave_btn': 'গ্রুপ ত্যাগ করুন',
    'groups.details.edit_btn': 'গ্রুপ এডিট করুন',
    'groups.details.delete_btn': 'গ্রুপ ডিলিট করুন',
    'groups.details.delete_confirm': 'আপনি কি নিশ্চিত যে আপনি এই গ্রুপটি ডিলিট করতে চান? এই কাজটি আর ফিরিয়ে আনা যাবে না।',
    'groups.details.social_links': 'সোশ্যাল লিঙ্ক',
    'groups.details.admin_badge': 'অ্যাডমিন',
    'groups.details.no_members': 'এই গ্রুপে এখনও কোনো সদস্য নেই।',
    'groups.details.add_member': 'সদস্য যোগ করুন',
    'groups.details.search_donors': 'সদস্য যোগ করতে দাতা খুঁজুন...',
    'groups.details.add_success': 'সদস্য সফলভাবে যোগ করা হয়েছে!',
    'groups.details.already_member': 'ইতিমধ্যে সদস্য',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved === 'en' || saved === 'bn') ? saved : 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
